name: Publish continuous release of Shimeji-Desktop

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      # https://github.com/marketplace/actions/setup-java-jdk
      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Cache Maven Packages
        uses: actions/cache@v5
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots -Dmaven.javadoc.skip=true verify --file pom.xml

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: my-artifact
          path: target/Shimeji-ee_*.zip

  release:
    needs: [ build ]
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.job }}
      cancel-in-progress: true

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v7

      - run: |
          gh release delete bleedingedge --cleanup-tag --yes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
        continue-on-error: true # In case the release doesn't exist and the execution fails

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: bleedingedge
          name: Bleeding edge
          prerelease: true
          fail_on_unmatched_files: true
          files: |
            **
          body: |
            This is the latest snapshot of Shimeji-Desktop. It has been automatically generated from the latest commit.
