name: Publish continuous release of Shimeji-Desktop

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 11
          cache: 'maven'

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots -Dmaven.javadoc.skip=true verify --file pom.xml

        # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@v5

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: artifact
          path: target/Shimeji-ee_*.zip

  release:
    needs: [ build ]
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.job }}
      cancel-in-progress: true

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v7

      - run: |
          gh release delete bleedingedge --cleanup-tag --yes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
        continue-on-error: true # In case the release doesn't exist and the execution fails

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: bleedingedge
          name: Bleeding edge
          prerelease: true
          fail_on_unmatched_files: true
          files: |
            **
          body: |
            This is the latest snapshot of Shimeji-Desktop. It has been automatically generated from the latest commit.
